// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxfZhWWwCh2Gzr7ox9TOc7ctcaUn3odXs',
    appId: '1:230391060889:web:2bd840f87cb7c46d025b08',
    messagingSenderId: '230391060889',
    projectId: 'sharyan-99352',
    authDomain: 'sharyan-99352.firebaseapp.com',
    storageBucket: 'sharyan-99352.firebasestorage.app',
    measurementId: 'G-SE1H1T138H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_tpvXUeGlBuKWt5tE7R4D6GdvW-JjtIs',
    appId: '1:230391060889:android:6a5ca4b3109d8629025b08',
    messagingSenderId: '230391060889',
    projectId: 'sharyan-99352',
    storageBucket: 'sharyan-99352.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUSoq2J0j6m-uVBmoRLqdNjYZls97ZNnw',
    appId: '1:230391060889:ios:e4a55fee82ddff73025b08',
    messagingSenderId: '230391060889',
    projectId: 'sharyan-99352',
    storageBucket: 'sharyan-99352.firebasestorage.app',
    iosBundleId: 'com.example.sharyan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUSoq2J0j6m-uVBmoRLqdNjYZls97ZNnw',
    appId: '1:230391060889:ios:e4a55fee82ddff73025b08',
    messagingSenderId: '230391060889',
    projectId: 'sharyan-99352',
    storageBucket: 'sharyan-99352.firebasestorage.app',
    iosBundleId: 'com.example.sharyan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxfZhWWwCh2Gzr7ox9TOc7ctcaUn3odXs',
    appId: '1:230391060889:web:2ab71d3a2d0ca944025b08',
    messagingSenderId: '230391060889',
    projectId: 'sharyan-99352',
    authDomain: 'sharyan-99352.firebaseapp.com',
    storageBucket: 'sharyan-99352.firebasestorage.app',
    measurementId: 'G-ZS49XYJEV8',
  );
}
